ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'duplex';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'building';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'tower';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'annex';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'apartmentWithAnnex';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'floorWithAnnex';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'rooftopVilla';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'driverRoom';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'chalet';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'sharedRoom';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'hotelRoom';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'traditionalHouse';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'twoFloorApartment';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'plaza';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'mall';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'floor';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'kiosk';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'workshop';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'land';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'leasedLand';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'station';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'showroom';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'atm';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'cinema';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'powerStation';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'telecomTower';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'hotel';--> statement-breakpoint
ALTER TYPE "unit_type" ADD VALUE IF NOT EXISTS 'parkingLot';