-- Seed Saudi cities into the lookups table (category "city"). Idempotent.
INSERT INTO "lookups" ("category", "key", "label_ar", "label_en", "sort_order", "company_id")
SELECT v.category, v.key, v.label_ar, v.label_en, v.sort_order, NULL
FROM (VALUES
  ('city', 'riyadh', 'الرياض', 'Riyadh', 1),
  ('city', 'al_kharj', 'الخرج', 'Al-Kharj', 2),
  ('city', 'al_majmaah', 'المجمعة', 'Al-Majmaah', 3),
  ('city', 'ad_dawadimi', 'الدوادمي', 'Ad-Dawadimi', 4),
  ('city', 'az_zulfi', 'الزلفي', 'Az-Zulfi', 5),
  ('city', 'al_quwayiyah', 'القويعية', 'Al-Quwayiyah', 6),
  ('city', 'wadi_al_dawasir', 'وادي الدواسر', 'Wadi Al-Dawasir', 7),
  ('city', 'al_aflaj', 'الأفلاج', 'Al-Aflaj', 8),
  ('city', 'shaqra', 'شقراء', 'Shaqra', 9),
  ('city', 'dharma', 'ضرما', 'Dharma', 10),
  ('city', 'al_hariq', 'الحريق', 'Al-Hariq', 11),
  ('city', 'marat', 'مرات', 'Marat', 12),
  ('city', 'jeddah', 'جدة', 'Jeddah', 13),
  ('city', 'makkah', 'مكة المكرمة', 'Makkah', 14),
  ('city', 'ta_if', 'الطائف', 'Ta''if', 15),
  ('city', 'rabigh', 'رابغ', 'Rabigh', 16),
  ('city', 'al_qunfudhah', 'القنفذة', 'Al-Qunfudhah', 17),
  ('city', 'al_layth', 'الليث', 'Al-Layth', 18),
  ('city', 'khulayyis', 'خليص', 'Khulayyis', 19),
  ('city', 'al_jumum', 'الجموم', 'Al-Jumum', 20),
  ('city', 'bahra', 'بحرة', 'Bahra', 21),
  ('city', 'dammam', 'الدمام', 'Dammam', 22),
  ('city', 'al_khobar', 'الخبر', 'Al-Khobar', 23),
  ('city', 'al_ahsa', 'الأحساء', 'Al-Ahsa', 24),
  ('city', 'al_jubail', 'الجبيل', 'Al-Jubail', 25),
  ('city', 'al_qatif', 'القطيف', 'Al-Qatif', 26),
  ('city', 'hafar_al_batin', 'حفر الباطن', 'Hafar Al-Batin', 27),
  ('city', 'dhahran', 'الظهران', 'Dhahran', 28),
  ('city', 'al_khafji', 'الخفجي', 'Al-Khafji', 29),
  ('city', 'buqayq', 'بقيق', 'Buqayq', 30),
  ('city', 'ras_tanura', 'رأس تنورة', 'Ras Tanura', 31),
  ('city', 'an_nuayriyah', 'النعيرية', 'An-Nuayriyah', 32),
  ('city', 'madinah', 'المدينة المنورة', 'Madinah', 33),
  ('city', 'yanbu', 'ينبع', 'Yanbu', 34),
  ('city', 'alula', 'العلا', 'AlUla', 35),
  ('city', 'al_wajh', 'الوجه', 'Al-Wajh', 36),
  ('city', 'badr', 'بدر', 'Badr', 37),
  ('city', 'al_mahd', 'المهد', 'Al-Mahd', 38),
  ('city', 'khaybar', 'خيبر', 'Khaybar', 39),
  ('city', 'abha', 'أبها', 'Abha', 40),
  ('city', 'khamis_mushait', 'خميس مشيط', 'Khamis Mushait', 41),
  ('city', 'bisha', 'بيشة', 'Bisha', 42),
  ('city', 'an_namas', 'النماص', 'An-Namas', 43),
  ('city', 'muhayil_asir', 'محايل عسير', 'Muhayil Asir', 44),
  ('city', 'sarat_abidah', 'سراة عبيدة', 'Sarat Abidah', 45),
  ('city', 'rijal_alma', 'رجال ألمع', 'Rijal Alma', 46),
  ('city', 'al_majardah', 'المجاردة', 'Al-Majardah', 47),
  ('city', 'tabuk', 'تبوك', 'Tabuk', 48),
  ('city', 'duba', 'ضباء', 'Duba', 49),
  ('city', 'haql', 'حقل', 'Haql', 50),
  ('city', 'umluj', 'أملج', 'Umluj', 51),
  ('city', 'tayma', 'تيماء', 'Tayma', 52),
  ('city', 'al_bad', 'البدع', 'Al-Bad', 53),
  ('city', 'buraydah', 'بريدة', 'Buraydah', 54),
  ('city', 'unayzah', 'عنيزة', 'Unayzah', 55),
  ('city', 'ar_rass', 'الرس', 'Ar-Rass', 56),
  ('city', 'al_bukayriyah', 'البكيرية', 'Al-Bukayriyah', 57),
  ('city', 'al_mudhnib', 'المذنب', 'Al-Mudhnib', 58),
  ('city', 'ash_shmasiyah', 'الشماسية', 'Ash-Shmasiyah', 59),
  ('city', 'uyun_al_jawaa', 'عيون الجواء', 'Uyun Al-Jawaa', 60),
  ('city', 'ha_il', 'حائل', 'Ha''il', 61),
  ('city', 'baqa', 'بقعاء', 'Baqa', 62),
  ('city', 'al_ghazalah', 'الغزالة', 'Al-Ghazalah', 63),
  ('city', 'ash_shannan', 'الشنان', 'Ash-Shannan', 64),
  ('city', 'al_hayt', 'الحائط', 'Al-Hayt', 65),
  ('city', 'jizan', 'جازان', 'Jizan', 66),
  ('city', 'sabya', 'صبيا', 'Sabya', 67),
  ('city', 'abu_arish', 'أبو عريش', 'Abu Arish', 68),
  ('city', 'ad_darb', 'الدرب', 'Ad-Darb', 69),
  ('city', 'samtah', 'صامطة', 'Samtah', 70),
  ('city', 'baysh', 'بيش', 'Baysh', 71),
  ('city', 'damad', 'ضمد', 'Damad', 72),
  ('city', 'ar_rayth', 'الريث', 'Ar-Rayth', 73),
  ('city', 'farasan', 'فرسان', 'Farasan', 74),
  ('city', 'najran', 'نجران', 'Najran', 75),
  ('city', 'sharorah', 'شرورة', 'Sharorah', 76),
  ('city', 'habuna', 'حبونا', 'Habuna', 77),
  ('city', 'badr_al_janoub', 'بدر الجنوب', 'Badr Al-Janoub', 78),
  ('city', 'yadamah', 'يدمه', 'Yadamah', 79),
  ('city', 'al_bahah', 'الباحة', 'Al-Bahah', 80),
  ('city', 'baljurashi', 'بلجرشي', 'Baljurashi', 81),
  ('city', 'al_mandiq', 'المندق', 'Al-Mandiq', 82),
  ('city', 'al_aqiq', 'العقيق', 'Al-Aqiq', 83),
  ('city', 'qilwah', 'قلوة', 'Qilwah', 84),
  ('city', 'al_mikhwah', 'المخواة', 'Al-Mikhwah', 85),
  ('city', 'arar', 'عرعر', 'Arar', 86),
  ('city', 'rafha', 'رفحاء', 'Rafha', 87),
  ('city', 'turaif', 'طريف', 'Turaif', 88),
  ('city', 'al_uwayqilah', 'العويقيلة', 'Al-Uwayqilah', 89),
  ('city', 'sakaka', 'سكاكا', 'Sakaka', 90),
  ('city', 'al_qurayyat', 'القريات', 'Al-Qurayyat', 91),
  ('city', 'dawmat_al_jandal', 'دومة الجندل', 'Dawmat Al-Jandal', 92),
  ('city', 'saudi', 'سعودي', 'Saudi', 93),
  ('city', 'egyptian', 'مصري', 'Egyptian', 94),
  ('city', 'yemeni', 'يمني', 'Yemeni', 95),
  ('city', 'sudanese', 'سوداني', 'Sudanese', 96),
  ('city', 'syrian', 'سوري', 'Syrian', 97),
  ('city', 'jordanian', 'أردني', 'Jordanian', 98),
  ('city', 'palestinian', 'فلسطيني', 'Palestinian', 99),
  ('city', 'lebanese', 'لبناني', 'Lebanese', 100),
  ('city', 'iraqi', 'عراقي', 'Iraqi', 101),
  ('city', 'emirati', 'إماراتي', 'Emirati', 102),
  ('city', 'kuwaiti', 'كويتي', 'Kuwaiti', 103),
  ('city', 'bahraini', 'بحريني', 'Bahraini', 104),
  ('city', 'qatari', 'قطري', 'Qatari', 105),
  ('city', 'omani', 'عُماني', 'Omani', 106),
  ('city', 'indian', 'هندي', 'Indian', 107),
  ('city', 'pakistani', 'باكستاني', 'Pakistani', 108),
  ('city', 'bangladeshi', 'بنغلاديشي', 'Bangladeshi', 109),
  ('city', 'filipino', 'فلبيني', 'Filipino', 110),
  ('city', 'indonesian', 'إندونيسي', 'Indonesian', 111),
  ('city', 'ethiopian', 'إثيوبي', 'Ethiopian', 112),
  ('city', 'american', 'أمريكي', 'American', 113),
  ('city', 'british', 'بريطاني', 'British', 114),
  ('city', 'french', 'فرنسي', 'French', 115),
  ('city', 'turkish', 'تركي', 'Turkish', 116),
  ('city', 'other', 'أخرى', 'Other', 117)
) AS v(category, key, label_ar, label_en, sort_order)
WHERE NOT EXISTS (
  SELECT 1 FROM "lookups" l WHERE l.category = v.category AND l.key = v.key AND l.company_id IS NULL
);
